<a href="https://colab.research.google.com/github/dulcioris/dulcioris/blob/main/Prac1_AMN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problema 3

**Creando el código**

In [ ]:
import numpy as np

def inversa_matriz(M):
    n = M.shape[0]

    # Paso a: Definir el arreglo [M|I]
    I = np.identity(n)
    MI = np.concatenate((M, I), axis=1)

    # Paso b: Convertir el primer elemento de la primera fila en 1
    for i in range(n):
        # Dividir el renglón i por el primer elemento para hacer M[i,i] = 1
        MI[i, :] = MI[i, :] / MI[i, i]

        # Paso c y d: Eliminar los elementos debajo del primer elemento en la columna i
        for j in range(i+1, n):
            MI[j, :] = MI[j, :] - MI[j, i] * MI[i, :]

    # Paso e: Eliminar los elementos sobre la diagonal
    for i in range(n-1, -1, -1):
        for j in range(i-1, -1, -1):
            MI[j, :] = MI[j, :] - MI[j, i] * MI[i, :]

    # Paso g: Extraer la matriz inversa de [I|M^-1]
    M_inv = MI[:, n:]

    return M_inv

def es_invertible(M):
    return np.linalg.det(M) != 0


Matriz **100x100**

In [ ]:
# Prueba con una matriz 100x100 generada aleatoriamente
M2 = np.random.randint(1, 100, size=(100, 100))
if es_invertible(M2):
    M2_inv = inversa_matriz(M2)
    print("Inversión exitosa para la matriz 100x100.")
else:
    print("La matriz 100x100 no es invertible.")

Inversión exitosa para la matriz 100x100.


Matrices del **problema 2**

In [ ]:
# Primer matriz
M1 = np.array([[4, -8, 5], [4, -7, 4], [3, -4, 2]])
# Verificación e inversión de las matrices
M1_inv = inversa_matriz(M1) if es_invertible(M1) else "No invertible"
M1_inv

array([[ 2., -4.,  3.],
       [ 4., -7.,  4.],
       [ 5., -8.,  4.]])

In [ ]:
# Segunda matriz
M2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Verificación e inversión de las matrices
M2_inv = inversa_matriz(M2) if es_invertible(M2) else "No invertible"
M2_inv

'No invertible'

# Problema 4

**a) Escribe un código en python, usando la paquetería numpy, para separar una matriz M en las submatrices A, B, C y R, para algunos enteros n y m.**



In [ ]:
import numpy as np

def separar_matriz(M, n, m):
    A = M[:n, :n]  # Submatriz A de tamaño n x n
    C = M[:n, n:]  # Submatriz C de tamaño n x m
    R = M[n:, :n]  # Submatriz R de tamaño m x n
    B = M[n:, n:]  # Submatriz B de tamaño m x m
    return A, B, C, R

# Ejemplo de uso
n, m = 2, 2
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

A, B, C, R = separar_matriz(M, n, m)
print("A:\n", A)
print("B:\n", B)
print("C:\n", C)
print("R:\n", R)

A:
 [[1 2]
 [5 6]]
B:
 [[11 12]
 [15 16]]
C:
 [[3 4]
 [7 8]]
R:
 [[ 9 10]
 [13 14]]


**b) Escribe un código para obtener los complementos de Schur de las las matrices A y B obtenidas en el inciso anterior. Puedes utilizar la función que escribiste en el problema 3 para obtener las matrices inversas correspondientes.**
(en esta parte el código me regresa cosas raras)

In [ ]:
def schur_complementos(A, B, C, R):
    A_inv = np.linalg.inv(A)  # Inversa de A
    B_inv = np.linalg.inv(B)  # Inversa de B

    S = B - R @ A_inv @ C  # Complemento de Schur de B
    T = A - C @ B_inv @ R  # Complemento de Schur de A

    return S, T

# Ejemplo de uso
S, T = schur_complementos(A, B, C, R)
print("S:\n", S)
print("T:\n", T)

S:
 [[0.00000000e+00 1.77635684e-15]
 [7.10542736e-15 8.88178420e-15]]
T:
 [[-1.42108547e-14 -1.06581410e-14]
 [-2.84217094e-14 -2.84217094e-14]]


In [ ]:
import numpy as np

def separar_matriz(M, n, m):
    A = M[:n, :n]
    B = M[n:, n:]
    C = M[:n, n:]
    R = M[n:, :n]
    return A, B, C, R

def calcular_complementos_de_schur(A, B, C, R):
    # Verificamos si A y B son invertibles antes de calcular los complementos
    if np.linalg.det(A) == 0:
        raise ValueError("La matriz A es singular y no se puede invertir.")
    if np.linalg.det(B) == 0:
        raise ValueError("La matriz B es singular y no se puede invertir.")

    A_inv = np.linalg.inv(A)
    B_inv = np.linalg.inv(B)

    # Calculamos los complementos de Schur S y T
    S = B - R @ A_inv @ C
    T = A - C @ B_inv @ R

    return S, T

# Ejemplo de uso con una matriz no singular
M = np.array([[4, 7, 2, 3],
              [8, 10, 1, 5],
              [6, 1, 3, 2],
              [4, 5, 9, 7]])

n, m = 2, 2
A, B, C, R = separar_matriz(M, n, m)
S, T = calcular_complementos_de_schur(A, B, C, R)

print("S:\n", S)
print("T:\n", T)

S:
 [[ 7.125 -0.125]
 [ 8.5    4.5  ]]
T:
 [[23.33333333  3.        ]
 [66.66666667  1.        ]]


**c) Escribe códigos para verificar que si A y S son no singulares**

In [ ]:
import numpy as np

def verificar_igualdad_inversa(M, A, B, C, R):
    # Verificar si la matriz M es singular
    if np.linalg.det(M) == 0:
        print("La matriz M es singular y no se puede invertir.")
        return False

    # Calcular la inversa de A y S
    A_inv = np.linalg.inv(A)
    S = B - R @ A_inv @ C

    # Verificar si S es singular
    if np.linalg.det(S) == 0:
        print("La matriz S es singular y no se puede invertir.")
        return False

    S_inv = np.linalg.inv(S)

    # Calcular la matriz inversa del bloque original
    M_inv = np.linalg.inv(M)

    # Calcular la inversa usando la expresión de la derecha
    upper_left = A_inv + A_inv @ C @ S_inv @ R @ A_inv
    upper_right = -A_inv @ C @ S_inv
    lower_left = -S_inv @ R @ A_inv
    lower_right = S_inv

    # Construir la matriz inversa utilizando la fórmula de Schur
    M_inv_schur = np.block([
        [upper_left, upper_right],
        [lower_left, lower_right]
    ])

    # Verificar si ambas matrices son iguales
    return np.allclose(M_inv, M_inv_schur)

# Ejemplo de uso
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

n, m = 2, 2
A, B, C, R = separar_matriz(M, n, m)
es_igual = verificar_igualdad_inversa(M, A, B, C, R)
print("¿La igualdad se cumple?:", es_igual)

La matriz M es singular y no se puede invertir.
¿La igualdad se cumple?: False


**d) Comparación Gauss-Jordan con Schur**

Gauss-Jordan

In [14]:
import numpy as np
import time

def gauss_jordan(A):
    n = len(A)
    A = A.astype(float)

    # Matriz identidad
    I = np.eye(n)

    # Concatenar A con la matriz identidad
    AI = np.hstack((A, I))

    for i in range(n):
        # Verificar si el pivote es cero
        if AI[i, i] == 0:
            raise ValueError("La matriz es singular y no se puede invertir usando Gauss-Jordan.")

        # Normalizar la fila i
        AI[i] = AI[i] / AI[i, i]

        # Hacer ceros los demás elementos de la columna i
        for j in range(n):
            if i != j:
                AI[j] = AI[j] - AI[j, i] * AI[i]

    # Separar la matriz identidad modificada de la inversa
    A_inv = AI[:, n:]

    return A_inv

# Ejemplo de uso con la matriz M
M = np.array([[4, 7, 2, 3],
              [8, 10, 1, 5],
              [6, 1, 3, 2],
              [4, 5, 9, 7]])

try:
    start_time = time.time()
    M_inv_gj = gauss_jordan(M)
    end_time = time.time()
    print("Matriz inversa usando Gauss-Jordan:\n", M_inv_gj)
    print("Tiempo con Gauss-Jordan: {:.6f} segundos".format(end_time - start_time))
except ValueError as e:
    print(e)

Matriz inversa usando Gauss-Jordan:
 [[-0.00566038  0.01698113  0.19056604 -0.06415094]
 [ 0.37735849 -0.13207547 -0.03773585 -0.05660377]
 [ 0.44150943 -0.3245283   0.13584906  0.00377358]
 [-0.83396226  0.50188679 -0.25660377  0.21509434]]
Tiempo con Gauss-Jordan: 0.000786 segundos


Schur

In [15]:
import numpy as np
import time

def calcular_inversa_schur(A, B, C, R):
    # Verificar si A y B son invertibles antes de continuar
    if np.linalg.det(A) == 0:
        raise ValueError("La matriz A es singular y no se puede invertir.")
    if np.linalg.det(B) == 0:
        raise ValueError("La matriz B es singular y no se puede invertir.")

    A_inv = np.linalg.inv(A)
    B_inv = np.linalg.inv(B)

    # Calcular los complementos de Schur
    S = B - R @ A_inv @ C
    T = A - C @ B_inv @ R

    # Verificar si S y T son invertibles antes de continuar
    if np.linalg.det(S) == 0:
        raise ValueError("La matriz S es singular y no se puede invertir.")
    if np.linalg.det(T) == 0:
        raise ValueError("La matriz T es singular y no se puede invertir.")

    S_inv = np.linalg.inv(S)
    T_inv = np.linalg.inv(T)

    # Calcular la inversa de la matriz original usando Schur
    upper_left = T_inv
    upper_right = -T_inv @ C @ B_inv
    lower_left = -B_inv @ R @ T_inv
    lower_right = B_inv + B_inv @ R @ T_inv @ C @ B_inv

    M_inv_schur = np.block([
        [upper_left, upper_right],
        [lower_left, lower_right]
    ])

    return M_inv_schur

# Ejemplo de uso con la matriz M
n, m = 2, 2
A, B, C, R = separar_matriz(M, n, m)

try:
    start_time = time.time()
    M_inv_schur = calcular_inversa_schur(A, B, C, R)
    end_time = time.time()
    print("Matriz inversa usando la fórmula de Schur:\n", M_inv_schur)
    print("Tiempo con la fórmula de Schur: {:.6f} segundos".format(end_time - start_time))
except ValueError as e:
    print(e)

Matriz inversa usando la fórmula de Schur:
 [[-0.00566038  0.01698113  0.19056604 -0.06415094]
 [ 0.37735849 -0.13207547 -0.03773585 -0.05660377]
 [ 0.44150943 -0.3245283   0.13584906  0.00377358]
 [-0.83396226  0.50188679 -0.25660377  0.21509434]]
Tiempo con la fórmula de Schur: 0.000529 segundos


Comparación de resultados

In [16]:
# Comparar las inversas obtenidas
if 'M_inv_gj' in locals() and 'M_inv_schur' in locals():
    inversas_iguales = np.allclose(M_inv_gj, M_inv_schur)
    print("¿La inversa es igual en ambos métodos?:", inversas_iguales)
else:
    print("No se pudieron calcular las inversas con ambos métodos debido a matrices singulares.")

¿La inversa es igual en ambos métodos?: True
